# NUMPY ARRAYS

1. Import numpy. Create an array with 10 elements all being zero.


## `np.zeros`

The `zeros` function creates an array containing any number of zeros:

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
arr2D=np.zeros((3,4))
print(arr2D.argsort().argsort())

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [21]:
arr2D.shape

(3, 4)

In [22]:
arr2D.size

12

## N-dimensional arrays
Create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [7]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type
Find the type of the nd array.

In [8]:
type(arr2D)

numpy.ndarray

## `np.full`
Creates a 3x4 matrix having value of 3.14 or pi for all its elements.

In [10]:
import math
arr1=np.ones((3,4))*math.pi
arr1

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

Create an array of floating point numbers from 1 to 5 with as step of 0.5

In [11]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Create an array of numbers between 0 and 5 with the value 5 also included.

In [3]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## `np.rand` and `np.randn`
Create `ndarray`s initialized with random values. Create a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution and normal distribution):

In [15]:
arrUd=np.random.rand(3,4)
arrUd

array([[0.40034801, 0.67716642, 0.88545575, 0.52472886],
       [0.94207659, 0.77010708, 0.55327399, 0.32198821],
       [0.06628332, 0.02168719, 0.1702412 , 0.36920778]])

Here's a 3x4 matrix containing random floats sampled from a univariate [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) (Gaussian distribution) of mean 0 and variance 1:

In [17]:
arrNd=np.random.randn(3,4)
arrNd

array([[ 1.18859704, -0.17732766,  0.50992801,  0.79347795],
       [-0.85852729,  0.88125207,  1.21529911, -1.8723278 ],
       [ 0.98340927,  0.98049352,  1.13107729,  0.71287299]])

Visualize the rand and randn distributions using histogram plot.

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt

In [66]:
plt.

TypeError: hist() missing 1 required positional argument: 'x'

Create an array with datatype as complex64 and print the values.

In [7]:
np.arange(1,5)+np.array(0)*1j

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

# Reshaping an array
## In place
Create and array of 24 integers and reshape it to contain 6 rows and 4 columns and print the rank.

In [21]:
arr2=np.arange(24)
arr2=arr2.reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Set item at row 2, col 4 to 999 (more about indexing below).

In [23]:
arr2[1,3]=999
arr2

array([[  0,   1,   2,   3],
       [  4,   5,   6, 999],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

Convert nd-array to 1-d array.

In [24]:
arr2.flatten()

array([  0,   1,   2,   3,   4,   5,   6, 999,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Create a calculator with using numpy arrays.
1. Perform arithmetic operations operations on a and b below. (`+`, `-`, `*`, `/`, `//`, `**`, etc.) can be used with `ndarray`s. 
2. Perform comparison operations also
3. Compute the statistics on a and b - mean, sum, min, max, std, var.
4. Also, include trignomeric functions.
5. Check if the elements in each array are greater than 10 and print the array elements when true. Use broadcasting.


In [14]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
#arithmetic operations
add=a+b
print(add)
sub=a-b
print(sub)
mul=a*b
print(mul)
div=a/b
print(div)
modDiv=a//b
print(modDiv)
power=a**b
print(power)
#comparision operations
aGret_b=a>b
print(aGret_b)
aLess_b=a<b
print(aLess_b)
aEqu_b=a>b
print(aEqu_b)
#statistic
print('mean= ',a.mean(),'\nsum= ',a.sum(),'\nmin= ',a.min(),'\nstd= ',a.std(),'\nvar= ',a.var())
print('mean= ',b.mean(),'\nsum= ',b.sum(),'\nmin= ',b.min(),'\nstd= ',b.std(),'\nvar= ',b.var())
#trignometric funcs
cos_values=np.cos(a)
print(cos_values)
tan_values=np.tan(a)
print(tan_values)
#broadcasting
c=[10]
comp10=a>c
print(comp10)

[19 27 35 43]
[ 9 19 29 39]
[70 92 96 82]
[ 2.8         5.75       10.66666667 20.5       ]
[ 2  5 10 20]
[537824 279841  32768   1681]
[ True  True  True  True]
[False False False False]
[ True  True  True  True]
mean=  27.5 
sum=  110 
min=  14 
std=  10.062305898749054 
var=  101.25
mean=  3.5 
sum=  14 
min=  2 
std=  1.118033988749895 
var=  1.25
[ 0.13673722 -0.53283302  0.83422336 -0.98733928]
[7.24460662 1.58815308 0.66100604 0.1606567 ]
[ True  True  True  True]


# Stacking arrays
Stack the arrays a and b horizontally and print the shape. 

In [15]:
arrStack=np.hstack((a,b))
arrStack

array([14, 23, 32, 41,  5,  4,  3,  2])

# Splitting arrays
Split the same back to a and b.

In [16]:
a,b=np.array_split(arrStack,2)
print(a,b)

[14 23 32 41] [5 4 3 2]


Now let's split it in three equal parts, vertically:

In [17]:
a,b,c=np.array_split(arrStack,3)
print(a,b,c)

[14 23 32] [41  5  4] [3 2]


# Transposing arrays
Create a 2d- array and do a transpose of it and print the dimensions.

In [49]:
a=np.array([[1,2,3,4,5],
  [6,7,8,9,10]])
print(a)
np.transpose(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
np.inner()